-- Create Bins table if not exists (for status tracking)
CREATE TABLE IF NOT EXISTS bins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bin_id TEXT NOT NULL UNIQUE,
  location TEXT NOT NULL,
  fill_level INTEGER NOT NULL DEFAULT 0,
  last_collection TIMESTAMPTZ DEFAULT NOW(),
  status TEXT CHECK (status IN ('critical', 'warning', 'normal')) DEFAULT 'normal'
);

-- Insert detected bin from logs if not exists
INSERT INTO bins (bin_id, location, fill_level, status)
VALUES 
  ('Bin_001', 'Main Entrance', 45, 'normal')
ON CONFLICT (bin_id) DO NOTHING;
