-- Create Hourly Activity Table
CREATE TABLE IF NOT EXISTS hourly_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hour TEXT NOT NULL UNIQUE,
  activity INTEGER NOT NULL DEFAULT 0
);

-- Seed Hourly Activity (Example Data)
INSERT INTO hourly_activity (hour, activity) VALUES
('06:00', 15), ('07:00', 30), ('08:00', 45), ('09:00', 80), ('10:00', 60),
('11:00', 50), ('12:00', 95), ('13:00', 85), ('14:00', 55), ('15:00', 40),
('16:00', 35), ('17:00', 20), ('18:00', 25), ('19:00', 15), ('20:00', 10)
ON CONFLICT (hour) DO UPDATE SET activity = EXCLUDED.activity;


-- Create Alerts Table
CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT CHECK (type IN ('critical', 'warning', 'info')) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Alerts (Example Data)
INSERT INTO alerts (type, message, created_at) VALUES
('critical', 'Bin_009 at Cafeteria overflow detected', NOW() - INTERVAL '10 minutes'),
('warning', 'Bin_003 battery low (15%)', NOW() - INTERVAL '1 hour'),
('info', 'Daily collection schedule started', NOW() - INTERVAL '4 hours');


-- Create Waste Composition Table (Fallback for when logs are empty)
CREATE TABLE IF NOT EXISTS waste_composition (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material TEXT NOT NULL,
  value INTEGER NOT NULL
);

-- Seed Waste Composition (Example Data)
INSERT INTO waste_composition (material, value) VALUES
('Plastic', 35),
('Paper', 25),
('Metal', 15),
('Organic', 20),
('Glass', 5);
