-- Run this in your Supabase SQL Editor to create the required tables

-- 1. Waste Collections (for Trends Chart)
CREATE TABLE IF NOT EXISTS waste_collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  metal INTEGER NOT NULL DEFAULT 0,
  plastic INTEGER NOT NULL DEFAULT 0,
  paper INTEGER NOT NULL DEFAULT 0,
  mixed_waste INTEGER NOT NULL DEFAULT 0
);

-- Sample Data for Trends
INSERT INTO waste_collections (date, metal, plastic, paper, mixed_waste) VALUES
('2023-10-23', 120, 200, 150, 100),
('2023-10-24', 130, 210, 140, 90),
('2023-10-25', 140, 220, 160, 110);


-- 2. Waste Composition (for Pie Chart)
CREATE TABLE IF NOT EXISTS waste_composition (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material TEXT NOT NULL,
  percentage INTEGER NOT NULL
);

-- Sample Data for Composition
INSERT INTO waste_composition (material, percentage) VALUES
('Plastic', 35),
('Paper', 25),
('Metal', 20),
('Mixed Waste', 20);


-- 3. Hourly Activity (for Bar Chart)
CREATE TABLE IF NOT EXISTS hourly_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hour TEXT NOT NULL,
  activity INTEGER NOT NULL
);

-- Sample Data for Activity
INSERT INTO hourly_activity (hour, activity) VALUES
('6AM', 12), ('8AM', 45), ('10AM', 78), ('12PM', 95), 
('2PM', 82), ('4PM', 68), ('6PM', 54), ('8PM', 32);


-- 4. Bins (for Status Table)
CREATE TABLE IF NOT EXISTS bins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- internal DB ID
  bin_id TEXT NOT NULL, -- Display ID like "BIN-001"
  location TEXT NOT NULL,
  fill_level INTEGER NOT NULL,
  last_collection TIMESTAMPTZ DEFAULT NOW(),
  status TEXT CHECK (status IN ('critical', 'warning', 'normal'))
);

-- Sample Data for Bins
INSERT INTO bins (bin_id, location, fill_level, last_collection, status) VALUES
('BIN-001', 'Engineering Building A', 87, NOW() - INTERVAL '2 hours', 'critical'),
('BIN-002', 'Student Center', 72, NOW() - INTERVAL '4 hours', 'warning'),
('BIN-003', 'Library Main', 45, NOW() - INTERVAL '6 hours', 'normal');


-- 5. Alerts (for Live Alerts List)
CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT CHECK (type IN ('critical', 'warning', 'info')),
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sample Data for Alerts
INSERT INTO alerts (type, message, created_at) VALUES
('critical', 'BIN-004 at 92% capacity - Collection needed', NOW() - INTERVAL '5 minutes'),
('warning', 'Unusual activity detected at Science Lab B', NOW() - INTERVAL '28 minutes');
