-- Run this in your Supabase SQL Editor to create the required tables

-- 1. Waste Collections (for Trends Chart)
CREATE TABLE IF NOT EXISTS waste_collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  recyclables INTEGER NOT NULL DEFAULT 0,
  organic INTEGER NOT NULL DEFAULT 0,
  general INTEGER NOT NULL DEFAULT 0
);

-- Sample Data for Trends
INSERT INTO waste_collections (date, recyclables, organic, general) VALUES
('2023-10-23', 420, 280, 180),
('2023-10-24', 380, 310, 150),
('2023-10-25', 450, 260, 190);


-- 2. Waste Composition (for Pie Chart)
CREATE TABLE IF NOT EXISTS waste_composition (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material TEXT NOT NULL,
  percentage INTEGER NOT NULL
);

-- Sample Data for Composition
INSERT INTO waste_composition (material, percentage) VALUES
('Plastics', 35),
('Paper', 28),
('Organic', 22),
('Metal', 10),
('Glass', 5);


-- 3. Hourly Activity (for Bar Chart)
CREATE TABLE IF NOT EXISTS hourly_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hour TEXT NOT NULL,
  activity INTEGER NOT NULL
);

-- Sample Data for Activity
INSERT INTO hourly_activity (hour, activity) VALUES
('6AM', 12), ('8AM', 45), ('10AM', 78), ('12PM', 95), 
('2PM', 82), ('4PM', 68), ('6PM', 54), ('8PM', 32);


-- 4. Bins (for Status Table)
CREATE TABLE IF NOT EXISTS bins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- internal DB ID
  bin_id TEXT NOT NULL, -- Display ID like "BIN-001"
  location TEXT NOT NULL,
  fill_level INTEGER NOT NULL,
  last_collection TIMESTAMPTZ DEFAULT NOW(),
  status TEXT CHECK (status IN ('critical', 'warning', 'normal'))
);

-- Sample Data for Bins
INSERT INTO bins (bin_id, location, fill_level, last_collection, status) VALUES
('BIN-001', 'Engineering Building A', 87, NOW() - INTERVAL '2 hours', 'critical'),
('BIN-002', 'Student Center', 72, NOW() - INTERVAL '4 hours', 'warning'),
('BIN-003', 'Library Main', 45, NOW() - INTERVAL '6 hours', 'normal');


-- 5. Alerts (for Live Alerts List)
CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT CHECK (type IN ('critical', 'warning', 'info')),
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sample Data for Alerts
INSERT INTO alerts (type, message, created_at) VALUES
('critical', 'BIN-004 at 92% capacity - Collection needed', NOW() - INTERVAL '5 minutes'),
('warning', 'Unusual activity detected at Science Lab B', NOW() - INTERVAL '28 minutes');
